/**
 * Generate docs/AUDIT.md — a reviewable record of every judgement call in this repo that
 * is not a direct copy of CoSAI data.
 *
 * Three sections:
 *   1. Map fidelity      — where each component sits, and how that compares to SAIF.
 *   2. Edge fidelity     — the full CoSAI edge list, and any prose/data tensions found.
 *   3. Overlay decisions — for each risk, the highlights and where they came from, with
 *                          CoSAI's own tour prose alongside so a reviewer can check them.
 *
 *   npm run audit
 */
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";
import { parse } from "yaml";

import { bandFor } from "../src/lib/bands";
import { EDGES } from "../src/lib/map-layout";
import type { Component, Control, Paragraph, Risk } from "../src/lib/types";
import { PHASES } from "../src/lib/types";

const ROOT = process.cwd();

/** Where the original SAIF map drew each component, for the comparison column. */
const SAIF_BAND: Record<string, string> = {
  componentDataSources: "data",
  componentDataFilteringAndProcessing: "data",
  componentTrainingData: "data",
  componentDataStorage: "infrastructure",
  componentModelEvaluation: "infrastructure",
  componentModelTrainingTuning: "infrastructure",
  componentModelFrameworksAndCode: "infrastructure",
  componentModelStorage: "infrastructure",
  componentModelServing: "infrastructure",
  componentTheModel: "model",
  componentApplicationInputHandling: "model",
  componentApplicationOutputHandling: "model",
  componentApplication: "application",
  componentReasoningCore: "application",
  componentAgentUserQuery: "application",
  componentAgentSystemInstruction: "application",
  componentAgentInputHandling: "application",
  componentAgentOutputHandling: "application",
  componentOrchestrationInputHandling: "application",
  componentOrchestrationOutputHandling: "application",
  componentTools: "application",
  componentRAGContent: "application",
  componentMemory: "application",
};

const flat = (p?: Paragraph[]) =>
  (p ?? [])
    .flatMap((x) => (Array.isArray(x) ? x : [x]))
    .join(" ")
    .replace(/\{\{ref:[^}]+\}\}/g, "")
    .replace(/\s+/g, " ")
    .trim();

async function main() {
  const components = (
    await parse(await readFile(join(ROOT, "data/cosai/components.yaml"), "utf8"))
  ).components as Component[];
  const risks = (await parse(await readFile(join(ROOT, "data/cosai/risks.yaml"), "utf8")))
    .risks as Risk[];
  const controls = (await parse(await readFile(join(ROOT, "data/cosai/controls.yaml"), "utf8")))
    .controls as Control[];
  const overlays = (
    await parse(await readFile(join(ROOT, "data/overlay/risk-components.yaml"), "utf8"))
  ).overlays as {
    risk: string;
    source: string;
    introduced: string[];
    exposed: string[];
    mitigated: string[] | "derived";
  }[];

  const byId = new Map(components.map((c) => [c.id, c]));
  const controlById = new Map(controls.map((c) => [c.id, c]));
  const overlayByRisk = new Map(overlays.map((o) => [o.risk, o]));

  // CoSAI reuses "Input Handling" / "Output Handling" across three layers; qualify them.
  const QUALIFIER: Record<string, string> = {
    componentApplicationInputHandling: "Application",
    componentApplicationOutputHandling: "Application",
    componentOrchestrationInputHandling: "Orchestration",
    componentOrchestrationOutputHandling: "Orchestration",
    componentAgentInputHandling: "Agent",
    componentAgentOutputHandling: "Agent",
  };
  const dupes = new Set(
    components.map((c) => c.title).filter((t, i, all) => all.indexOf(t) !== i),
  );
  const title = (id: string) => {
    const c = byId.get(id);
    if (!c) return id;
    return dupes.has(c.title) && QUALIFIER[id] ? `${QUALIFIER[id]} ${c.title}` : c.title;
  };

  const out: string[] = [];
  const p = (s = "") => out.push(s);

  p("# Audit");
  p();
  p(
    "Generated by `npm run audit`. Everything here is checked against the vendored CoSAI " +
      "snapshot at build time; `npm run build` fails if the map or the overlay drifts from it.",
  );
  p();

  // --- 1. Components ------------------------------------------------------------------
  p("## 1. Component placement");
  p();
  p(
    "Band assignment is computed from each component's own `category` / `subcategory` in " +
      "`components.yaml` (see `src/lib/bands.ts`) — no component is placed by hand. The last " +
      "column shows where Google's SAIF map drew the same component, so the divergences are " +
      "explicit.",
  );
  p();
  p("| Component | CoSAI category / subcategory | Our band | SAIF band | |");
  p("| --- | --- | --- | --- | --- |");

  const moved: string[] = [];
  for (const c of components) {
    const band = bandFor(c.category, c.subcategory);
    const saif = SAIF_BAND[c.id];
    const differs = saif && saif !== band;
    if (differs) moved.push(c.id);
    p(
      `| ${title(c.id)} | \`${c.category}\` / \`${c.subcategory ?? "—"}\` | **${band}** | ${saif ?? "—"} | ${
        differs ? "moved" : ""
      } |`,
    );
  }
  p();
  p(
    `${components.length} components, all drawn on the map. ${moved.length} sit in a different ` +
      "band than SAIF used, because CoSAI classifies them differently:",
  );
  p();
  for (const id of moved) {
    const c = byId.get(id)!;
    p(
      `- **${title(c.id)}** — SAIF: ${SAIF_BAND[id]}; CoSAI: \`${c.category}\`/\`${c.subcategory}\` ` +
        `→ ${bandFor(c.category, c.subcategory)}.`,
    );
  }
  p();

  // --- 2. Edges -----------------------------------------------------------------------
  p("## 2. Flows");
  p();
  p(
    "Every arrow on the map is an edge declared in `components.yaml`, and every declared edge " +
      "is drawn. The build compares the two sets and fails on any addition, omission or " +
      "reversal, so the arrows cannot drift from CoSAI.",
  );
  p();
  p("| From | To |");
  p("| --- | --- |");
  for (const e of [...EDGES].sort((a, b) => a.from.localeCompare(b.from))) {
    p(`| ${title(e.from)} | ${title(e.to)} |`);
  }
  p();
  p(`${EDGES.length} edges.`);
  p();
  p("### Known tension in the upstream data");
  p();
  p(
    "CoSAI's edge list and CoSAI's prose disagree about the Application core round trip. " +
      "The edges say `Application → Output Handling → The Model` and " +
      "`The Model → Input Handling → Application` — an application-centric reading, where " +
      "output handling is what the app sends out. The prose for Output Handling instead says it " +
      "protects against *\"dangerous outputs from a model\"*, a model-centric reading that matches " +
      "SAIF's original diagram, where the arrows run the other way.",
  );
  p();
  p(
    "**We follow the edge data**, because it is the machine-readable artefact CoSAI validates " +
      "in its own CI, and because following it lets the build prove the map matches the source. " +
      "This is the one place where the map deliberately differs from the SAIF diagram's arrow " +
      "direction, and it is worth raising upstream.",
  );
  p();

  // --- 3. Overlay ---------------------------------------------------------------------
  p("## 3. Risk highlights");
  p();
  p(
    "CoSAI publishes `tourContent` prose for introduced / exposed / mitigated but no component " +
      "id lists, so the map needs a mapping from that prose to component ids. That mapping is " +
      "`data/overlay/risk-components.yaml`, and it has two provenances:",
  );
  p();
  p(
    "- **`saif`** — the 15 risks CoSAI inherited from SAIF. Highlights are Google's own, " +
      "extracted from the public SAIF Map bundle and translated onto CoSAI ids. Re-verified on " +
      "every build against `data/overlay/saif-tour-seed.json`.",
  );
  p(
    "- **`authored`** — the 21 risks CoSAI added afterwards. No upstream mapping exists. Each " +
      "was written by reading that risk's own `tourContent` prose and naming the components it " +
      "describes, then cross-checked against the components its mapped controls protect. " +
      "**These are editorial judgements and are the part of this repo most worth reviewing.** " +
      "Each entry below shows CoSAI's prose next to the ids chosen from it.",
  );
  p();

  const authored = risks.filter((r) => overlayByRisk.get(r.id)?.source === "authored");
  const seeded = risks.filter((r) => overlayByRisk.get(r.id)?.source === "saif");

  p(`### 3a. Authored — ${authored.length} risks`);
  p();
  for (const risk of authored) {
    const o = overlayByRisk.get(risk.id)!;
    p(`#### ${risk.title}`);
    p();
    p(`\`${risk.id}\` · category \`${risk.category}\``);
    p();
    for (const phase of PHASES) {
      const prose = flat(risk.tourContent?.[phase]);
      const ids = (phase === "mitigated" && o.mitigated === "derived" ? [] : o[phase]) as string[];
      p(`**${phase[0].toUpperCase() + phase.slice(1)}**`);
      p();
      p(`> ${prose || "_no prose in CoSAI_"}`);
      p();
      p(`Chosen: ${ids.length ? ids.map((id) => `\`${title(id)}\``).join(", ") : "_derived_"}`);
      p();
    }
    const derived = new Set<string>();
    for (const cid of risk.controls) {
      const control = controlById.get(cid);
      if (Array.isArray(control?.components)) control.components.forEach((x) => derived.add(x));
    }
    p(
      `Components protected by this risk's ${risk.controls.length} controls, for comparison: ` +
        `${[...derived].map((id) => title(id)).join(", ") || "none"}`,
    );
    p();
  }

  p(`### 3b. SAIF-seeded — ${seeded.length} risks`);
  p();
  p("Highlights below are Google's original mapping, not ours.");
  p();
  p("| Risk | Introduced | Exposed | Mitigated |");
  p("| --- | --- | --- | --- |");
  for (const risk of seeded) {
    const o = overlayByRisk.get(risk.id)!;
    const cell = (ids: string[] | "derived") =>
      ids === "derived" ? "_derived_" : ids.map((id) => title(id)).join(", ");
    p(
      `| ${risk.title} | ${cell(o.introduced)} | ${cell(o.exposed)} | ${cell(o.mitigated)} |`,
    );
  }
  p();

  await mkdir(join(ROOT, "docs"), { recursive: true });
  await writeFile(join(ROOT, "docs", "AUDIT.md"), out.join("\n"));
  console.log(
    `docs/AUDIT.md: ${components.length} components, ${EDGES.length} edges, ` +
      `${authored.length} authored + ${seeded.length} seeded overlays`,
  );
}

main();
