/**
 * Generate docs/AUDIT.md — a reviewable record of every judgement call in this repo that
 * is not a direct copy of CoSAI data.
 *
 * Three sections:
 *   1. Map fidelity      — where each component sits, and how that compares to SAIF.
 *   2. Edge fidelity     — the full CoSAI edge list, and any prose/data tensions found.
 *   3. Overlay decisions — for each risk, the highlights and where they came from, with
 *                          CoSAI's own tour prose alongside so a reviewer can check them.
 *   4. Archetype coverage — which risks, capabilities and components no reference architecture
 *                          reaches, and which classes of control the catalogue requires.
 *
 *   npm run audit
 */
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";
import { parse } from "yaml";

import { BAND_DEVIATIONS, bandFor, cosaiBandFor } from "../src/lib/bands";
import { ACTORS, CONTAINMENT_EDGES, EDGE_DEVIATIONS, EDGES, UNDRAWN_EDGES } from "../src/lib/map-layout";
import { DISPLAY_NAME, NAME_REASON } from "../src/lib/naming";
import type {
  Archetype,
  Capability,
  Component,
  Control,
  Paragraph,
  Risk,
  Surface,
} from "../src/lib/types";
import { PHASES } from "../src/lib/types";

const ROOT = process.cwd();

const flat = (p?: Paragraph[]) =>
  (p ?? [])
    .flatMap((x) => (Array.isArray(x) ? x : [x]))
    .join(" ")
    .replace(/\{\{ref:[^}]+\}\}/g, "")
    .replace(/\s+/g, " ")
    .trim();

async function main() {
  const components = (
    await parse(await readFile(join(ROOT, "data/cosai/components.yaml"), "utf8"))
  ).components as Component[];
  const risks = (await parse(await readFile(join(ROOT, "data/cosai/risks.yaml"), "utf8")))
    .risks as Risk[];
  const controls = (await parse(await readFile(join(ROOT, "data/cosai/controls.yaml"), "utf8")))
    .controls as Control[];
  const overlays = (
    await parse(await readFile(join(ROOT, "data/overlay/risk-components.yaml"), "utf8"))
  ).overlays as {
    risk: string;
    source: string;
    introduced: string[];
    exposed: string[];
    mitigated: string[] | "derived";
  }[];

  const byId = new Map(components.map((c) => [c.id, c]));
  const controlById = new Map(controls.map((c) => [c.id, c]));
  const overlayByRisk = new Map(overlays.map((o) => [o.risk, o]));

  const title = (id: string) => DISPLAY_NAME[id] ?? byId.get(id)?.title ?? id;

  const out: string[] = [];
  const p = (s = "") => out.push(s);

  p("# Audit");
  p();
  p(
    "Generated by `npm run audit`. Everything here is checked against the vendored CoSAI " +
      "snapshot at build time; `npm run build` fails if the map or the overlay drifts from it.",
  );
  p();

  // --- 1. Components ------------------------------------------------------------------
  p("## 1. Component placement");
  p();
  p(
    "Every box on the map is a CoSAI component. Band assignment starts from each " +
      "component's own `category` / `subcategory` in `components.yaml`, and any divergence " +
      "from that must be declared with a reason in `BAND_DEVIATIONS` (`src/lib/bands.ts`). " +
      "The arrangement follows SAIF's stacked layout because that is what makes the diagram " +
      "readable — the taxonomy is CoSAI's, the composition is SAIF's.",
  );
  p();
  p("| Component | CoSAI category / subcategory | CoSAI band | Drawn in | |");
  p("| --- | --- | --- | --- | --- |");

  const deviated: string[] = [];
  for (const c of components) {
    const band = bandFor(c.id, c.category, c.subcategory);
    const cosai = cosaiBandFor(c.category, c.subcategory);
    const differs = band !== cosai;
    if (differs) deviated.push(c.id);
    p(
      `| ${title(c.id)} | \`${c.category}\` / \`${c.subcategory ?? "—"}\` | ${cosai} | **${band}** | ${
        differs ? "deviation" : ""
      } |`,
    );
  }
  p();
  p(
    `${components.length} components, all drawn on the map. ${deviated.length} are drawn ` +
      "outside the band CoSAI's classification implies. Each is a deliberate, declared choice " +
      "in `BAND_DEVIATIONS` (`src/lib/bands.ts`); the build fails on any undeclared divergence:",
  );
  p();
  for (const id of deviated) {
    p(`- **${title(id)}** — ${BAND_DEVIATIONS[id]?.reason ?? "undocumented"}`);
  }
  p();

  p("### Boundary actors");
  p();
  p(
    "The map also draws what sits *outside* the system. CoSAI models the system only, so " +
      "these are not components and are excluded from the coverage check — but SAIF drew them, " +
      "and they are where untrusted input and third-party services cross the boundary. Risks " +
      "and incident steps may name them, and they highlight like any component.",
  );
  p();
  p("| Actor | Boundary it marks |");
  p("| --- | --- |");
  for (const a of ACTORS) p(`| ${a.label} (\`${a.id}\`) | ${a.hint} |`);
  p();

  p("### Display names");
  p();
  p(
    "CoSAI's titles are written for a table, where a category column disambiguates them — " +
      "three components are titled “Input Handling” and three “Output Handling”. These are " +
      "renamed for the diagram, consistently everywhere in the product, with CoSAI's own " +
      "title always shown on the Components tab.",
  );
  p();
  p("| CoSAI title | Shown as | Why |");
  p("| --- | --- | --- |");
  for (const [id, name] of Object.entries(DISPLAY_NAME)) {
    p(`| ${byId.get(id)?.title ?? id} | **${name}** | ${NAME_REASON[id] ?? ""} |`);
  }
  p();

  // --- 2. Edges -----------------------------------------------------------------------
  p("## 2. Flows");
  p();
  p(
    "Every arrow on the map is an edge declared in `components.yaml` — nothing is invented. " +
      "CoSAI declares 32 edges; drawing all of them turns the picture into a wiring diagram, " +
      "so a small number are deliberately left out and listed below. The build fails if an " +
      "edge is drawn that CoSAI does not declare, or if a declared edge is neither drawn nor " +
      "documented as undrawn.",
  );
  p();
  p("| From | To |");
  p("| --- | --- |");
  for (const e of [...EDGES].sort((a, b) => a.from.localeCompare(b.from))) {
    p(`| ${title(e.from)} | ${title(e.to)} |`);
  }
  p();
  p(`${EDGES.length} edges drawn.`);
  p();
  p("### Edges drawn in the opposite direction");
  p();
  for (const e of EDGE_DEVIATIONS) {
    p(`- **${title(e.from)} → ${title(e.to)}** — ${e.reason}`);
  }
  p();
  p("### Routing convention at the agent boundary");
  p();
  p(
    "Four flows cross between the application layer and the model: the application's round " +
      "trip through the model handlers, and the agent's own round trip through the model. " +
      "Drawing each to its exact component means routing a line around the entire agent. " +
      "Following SAIF, these four are drawn as short arrows meeting the Agent group's edge, " +
      "with the group standing in for the component inside it. The declared endpoints are " +
      "unchanged and still checked by the build — only the drawn geometry is abbreviated.",
  );
  p();
  p("### Edges shown by nesting");
  p();
  for (const e of CONTAINMENT_EDGES) {
    p(`- **${title(e.from)} → ${title(e.to)}** — ${e.reason}`);
  }
  p();
  p("### Declared edges not drawn");
  p();
  for (const e of UNDRAWN_EDGES) {
    p(`- **${title(e.from)} → ${title(e.to)}** — ${e.reason}`);
  }
  p();
  p(
    "Both remain visible in the product: the Components tab lists every component's full " +
      "`receives from` / `sends to` set, so no CoSAI relationship is hidden.",
  );
  p();
  p("### Known tension in the upstream data");
  p();
  p(
    "CoSAI's edge list and CoSAI's prose disagree about the Application core round trip. " +
      "The edges say `Application → Output Handling → The Model` and " +
      "`The Model → Input Handling → Application` — an application-centric reading, where " +
      "output handling is what the app sends out. The prose for Output Handling instead says it " +
      "protects against *\"dangerous outputs from a model\"*, a model-centric reading that matches " +
      "SAIF's original diagram, where the arrows run the other way.",
  );
  p();
  p(
    "**We follow the edge data**, because it is the machine-readable artefact CoSAI validates " +
      "in its own CI, and because following it lets the build prove the map matches the source. " +
      "This is the one place where the map deliberately differs from the SAIF diagram's arrow " +
      "direction, and it is worth raising upstream.",
  );
  p();

  // --- 3. Overlay ---------------------------------------------------------------------
  p("## 3. Risk highlights");
  p();
  p(
    "CoSAI publishes `tourContent` prose for introduced / exposed / mitigated but no component " +
      "id lists, so the map needs a mapping from that prose to component ids. That mapping is " +
      "`data/overlay/risk-components.yaml`, and it has two provenances:",
  );
  p();
  p(
    "- **`saif`** — the 15 risks CoSAI inherited from SAIF. Highlights are Google's own, " +
      "extracted from the public SAIF Map bundle and translated onto CoSAI ids. Re-verified on " +
      "every build against `data/overlay/saif-tour-seed.json`.",
  );
  p(
    "- **`authored`** — the 21 risks CoSAI added afterwards. No upstream mapping exists. Each " +
      "was written by reading that risk's own `tourContent` prose and naming the components it " +
      "describes, then cross-checked against the components its mapped controls protect. " +
      "**These are editorial judgements and are the part of this repo most worth reviewing.** " +
      "Each entry below shows CoSAI's prose next to the ids chosen from it.",
  );
  p();

  const authored = risks.filter((r) => overlayByRisk.get(r.id)?.source === "authored");
  const seeded = risks.filter((r) => overlayByRisk.get(r.id)?.source === "saif");

  p(`### 3a. Authored — ${authored.length} risks`);
  p();
  for (const risk of authored) {
    const o = overlayByRisk.get(risk.id)!;
    p(`#### ${risk.title}`);
    p();
    p(`\`${risk.id}\` · category \`${risk.category}\``);
    p();
    for (const phase of PHASES) {
      const prose = flat(risk.tourContent?.[phase]);
      const ids = (phase === "mitigated" && o.mitigated === "derived" ? [] : o[phase]) as string[];
      p(`**${phase[0].toUpperCase() + phase.slice(1)}**`);
      p();
      p(`> ${prose || "_no prose in CoSAI_"}`);
      p();
      p(`Chosen: ${ids.length ? ids.map((id) => `\`${title(id)}\``).join(", ") : "_derived_"}`);
      p();
    }
    const derived = new Set<string>();
    for (const cid of risk.controls) {
      const control = controlById.get(cid);
      if (Array.isArray(control?.components)) control.components.forEach((x) => derived.add(x));
    }
    p(
      `Components protected by this risk's ${risk.controls.length} controls, for comparison: ` +
        `${[...derived].map((id) => title(id)).join(", ") || "none"}`,
    );
    p();
  }

  p(`### 3b. SAIF-seeded — ${seeded.length} risks`);
  p();
  p("Highlights below are Google's original mapping, not ours.");
  p();
  p("| Risk | Introduced | Exposed | Mitigated |");
  p("| --- | --- | --- | --- |");
  for (const risk of seeded) {
    const o = overlayByRisk.get(risk.id)!;
    const cell = (ids: string[] | "derived") =>
      ids === "derived" ? "_derived_" : ids.map((id) => title(id)).join(", ");
    p(
      `| ${risk.title} | ${cell(o.introduced)} | ${cell(o.exposed)} | ${cell(o.mitigated)} |`,
    );
  }
  p();

  // --- 4. Architecture coverage -------------------------------------------------------
  // Read from the generated dataset rather than the YAML, because the build has already
  // resolved and validated it. The catalogue is mid-rebuild: the zone-style set is archived
  // and the flow-style pilots replace it one architecture at a time, so the gaps below are
  // expected to be large until the rebuild lands — they are the work list, not a regression.
  const dataset = JSON.parse(
    await readFile(join(ROOT, "src/data/generated/dataset.json"), "utf8"),
  ) as { archetypes: Archetype[]; capabilities: Capability[]; surfaces: Surface[] };
  const archetypes = dataset.archetypes ?? [];

  p("## 4. Architecture coverage");
  p();
  p(
    `${archetypes.length} flow-style reference architectures (pilots; the 28-archetype ` +
      "zone-style catalogue is archived under data/reference/archive). Everything below is a " +
      "gap between the taxonomy and the drawings.",
  );
  p();

  p("| Surface | Architectures |");
  p("| --- | --- |");
  for (const surface of dataset.surfaces) {
    const named = archetypes.filter((a) => a.surface === surface.id);
    p(`| ${surface.title} | ${named.length ? `${named.length} — ${named.map((a) => a.title).join(", ")}` : "none yet"} |`);
  }
  p();

  const namedRisks = new Set(archetypes.flatMap((a) => a.risks));
  const unreachedRisks = risks.filter((r) => !namedRisks.has(r.id));
  p(`### 4a. Risks no architecture pins — ${unreachedRisks.length} of ${risks.length}`);
  p();
  p(
    unreachedRisks.length
      ? unreachedRisks.map((r) => `- ${r.title} (\`${r.id}\`)`).join("\n")
      : "_None. Every CoSAI risk is pinned in at least one reference architecture._",
  );
  p();

  const namedCaps = new Set(archetypes.flatMap((a) => a.capabilities));
  const unusedCaps = dataset.capabilities.filter((c) => !namedCaps.has(c.id));
  p(`### 4b. Capabilities no architecture pins — ${unusedCaps.length} of ${dataset.capabilities.length}`);
  p();
  p(
    unusedCaps.length
      ? unusedCaps.map((c) => `- ${c.title} (\`${c.id}\`)`).join("\n")
      : "_None. Every capability in the taxonomy is pinned somewhere._",
  );
  p();

  const anchored = new Set(
    archetypes.flatMap((a) => [
      ...a.blocks.map((b) => b.cosaiComponent),
      ...a.blocks.flatMap((b) => (b.items ?? []).map((i) => i.cosaiComponent)),
    ]).filter(Boolean) as string[],
  );
  const unanchored = components.filter((c) => !anchored.has(c.id));
  p(`### 4c. CoSAI components no architecture anchors — ${unanchored.length} of ${components.length}`);
  p();
  p(
    unanchored.length
      ? unanchored.map((c) => `- ${title(c.id)} (\`${c.id}\`)`).join("\n")
      : "_None. Every CoSAI component is anchored by at least one block or block internal._",
  );
  p();

  // 4d. The full anchor table: what every block claims to be in CoSAI terms, and therefore
  // which band colours its tab. "(none)" is a deliberate statement — CoSAI names no component
  // for gateways, sandboxes, governance planes or anything outside the system — and it is
  // exactly what the neutral tab on the diagram means.
  p(`### 4d. Block anchors — what each drawing claims in CoSAI terms`);
  p();
  p("| Architecture | Block | Kind | CoSAI anchor |");
  p("| --- | --- | --- | --- |");
  for (const a of archetypes) {
    for (const b of a.blocks) {
      if (b.kind === "actor") continue;
      const anchorId =
        b.cosaiComponent ?? (b.items ?? []).find((i) => i.cosaiComponent)?.cosaiComponent;
      p(
        `| ${a.title} | ${b.title} | ${b.kind} | ${anchorId ? `\`${anchorId}\`` : "(none)"} |`,
      );
    }
  }
  p();

  await mkdir(join(ROOT, "docs"), { recursive: true });
  await writeFile(join(ROOT, "docs", "AUDIT.md"), out.join("\n"));
  console.log(
    `docs/AUDIT.md: ${components.length} components, ${EDGES.length} edges, ` +
      `${authored.length} authored + ${seeded.length} seeded overlays, ` +
      `${archetypes.length} flow-style architectures (${unreachedRisks.length} risks and ` +
      `${unusedCaps.length} capabilities not yet pinned)`,
  );
}

main();
